version: '3.8'

services:
  market-data:
    build:
      context: ../market-data
      dockerfile: Dockerfile
    container_name: crypto-market-data
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - PYTHONUNBUFFERED=1
    volumes:
      - ../market-data:/app
    working_dir: /app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crypto-network

  telegram-bot:
    build:
      context: ../telegram-bot
      dockerfile: Dockerfile
    container_name: crypto-telegram-bot
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - MARKET_DATA_URL=http://crypto-market-data:8001
    volumes:
      - ../telegram-bot:/app
    working_dir: /app
    depends_on:
      - market-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crypto-network

networks:
  crypto-network:
    driver: bridge

volumes:
  postgres_data: